name: WorldEdit
main: com.sk89q.worldedit.bukkit.WorldEditPlugin
version: "${internalVersion}"
load: STARTUP
api-version: 1.13
softdepend: [Vault]
author: EngineHub
folia-supported: true
website: https://enginehub.org/worldedit